## Multiple Linear Regression

Multiple, bir y eksenine birden fazla unsurun etki etmesi demektir.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv("multiple_linear_regression_dataset.csv", sep=";")

In [3]:
df.head()

deneyim  maas  yas
0      0.5  2500   22
1      0.0  2250   21
2      1.0  2750   23
3      5.0  8000   25
4      8.0  9000   28

Çıktıda gördüğünüz üzere maas değerini deneyim ve yas deature'leri etkilemektedir. Buda multiple durumudur.

<font color="OliveDrab"><br>
Multiple linear regression denklemi : y = b0 + b1 * x1 + b2 * x2

maas değerini hem deneyim değeri hemde yas değeri etkilemektedir. Bu denklemde x1 deneyimi, x2 de yaşı ifade etmektedir.
    
Burada maas 'dependent variable' dir. Yani maas bağımlı değişkendir çünkü maas, deneyim ve yas değerlerine bağımlıdır. 
    
Burada deneyim ve yas 'independent variable' dir.
    
b0, b1, b2 değerlerini MSE değerini mimimum yapacak şekilde seçmeliyiz.
    
MSE: Gerçek değer ile tahmin edilen değer arasındaki farkın karesi alınır. Bu işlem her bir sample için uygulanır. Sonrasında elde edilen her bir değer toplanır ve sample sayısına bölünür. Elde edilen değer MSE 'dir.
    
Multiple linear regression'un linear regression'dan farkı, feature sayısının 1'den fazla olmasıdır.

In [4]:
x = df.iloc[:,[0,2]].values
y = df.maas.values.reshape(-1,1)

In [5]:
multile_linear_regression = LinearRegression()
multile_linear_regression.fit(x,y)

LinearRegression()

Şimdi b0, b1 ve b2 değerlerini bulalım.

In [6]:
b0 = multile_linear_regression.intercept_
b0

array([10376.62747228])

In [7]:
b1 = multile_linear_regression.coef_
b2 = multile_linear_regression.coef_
b1
b2

array([[1525.50072054, -416.72218625]])

In [8]:
multile_linear_regression.predict(np.array([[10,35],[5,35]]))

array([[11046.35815877],
       [ 3418.85455609]])

Yukarıda, deneyim=10, yas=35 ve deneyim=5, yas=35 değerleri ile tahmin gerçekleştirdik. 

Çıktıda, yaşlar aynı olmasına rağmen 5 yıllık bir deneyim farkının maaş konusunda ne kadar fark yarattığını görüyoruz.